# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    shm_size: '1g'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ../frog-gbif-volumes/mysql-data:/var/lib/mysql
      - ../frog-gbif-volumes/bucket:/bucket

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080